import requests
import json
import time
import sys

# Ensure utf-8 encoding for printing emojis on Windows
sys.stdout.reconfigure(encoding='utf-8')

BASE_URL = "http://localhost:8000"
USER_ID = 104
SESSION_ID = f"debate_test_{int(time.time())}"

def print_header(title):
    print(f"\n{'='*70}")
    print(f" {title}")
    print(f"{'='*70}")

def print_scenario(num, desc):
    print(f"\n--- Scenario {num}: {desc} ---")

def print_result(success, message, payload=None):
    icon = "✅ SUCCESS" if success else "❌ FAILED"
    print(f"  {icon} | {message}")
    if payload:
        if isinstance(payload, dict):
            # Print specifically for debate payload readability
            if "ai_message" in payload:
                print("\n  [AI RESPONSE]:")
                print(f"  \"{payload['ai_message']}\"\n")
            if "structured_data" in payload:
                usage = payload["structured_data"].get("usage", {})
                print(f"  [METADATA] Cost: ${usage.get('estimated_cost_usd', 0):.6f} | Generated By: {payload['structured_data']['practiceContent']['generatedBy']}")
            
            # Always print the full JSON so the user can see exactly what the backend team will receive
            print("\n  [FULL RAW RESPONSE PAYLOAD]:")
            print(f"  {json.dumps(payload, indent=2)}")
    
    if not success:
         print("\nStopping tests due to failure.")
         exit(1)

def run_tests():
    print_header("FLOW 04: DEBATE COACH PERSONA")
    
    try:
        requests.get(f"{BASE_URL}/health")
    except requests.exceptions.ConnectionError:
        print("❌ ERROR: Server is not running! Please start uvicorn app.main:app --reload first.")
        return

    # Setup
    print("Setting up background data...")
    cat = requests.post(f"{BASE_URL}/categories/", json={"user_id": USER_ID, "category_name": "Technology"}).json()
    top = requests.post(f"{BASE_URL}/topics/", json={"user_id": USER_ID, "category_id": cat["category_id"], "topic_name": "Universal Basic Income"}).json()
    topic_id = top["topic_id"]
    requests.post(f"{BASE_URL}/topics/{topic_id}/generate-materials", json={"user_id": USER_ID, "topic_id": topic_id, "topic_name": "Universal Basic Income", "difficulty": 4})

    # --- Scenario 1: Initial Argument ---
    print_scenario("1", "User provides an initial 'argument'")
    req_json = {
        "userId": USER_ID,
        "session_id": SESSION_ID,
        "topicId": topic_id,
        "difficulty": 4,
        "role": "argument",
        "message": "Universal Basic Income is necessary because automation will displace millions of workers in the next decade."
    }
    print(f"  User Role: {req_json['role']}")
    print(f"  User Msg: \"{req_json['message']}\"")
    print(f"  Payload sent:\n  {json.dumps(req_json, indent=2)}")
    
    resp1 = requests.post(f"{BASE_URL}/training/debate", json=req_json)
    success1 = resp1.status_code == 200
    print_result(success1, f"Debate API Status {resp1.status_code}", resp1.json() if success1 else resp1.text)


    # --- Scenario 2: Memory & Counter-Argument ---
    print_scenario("2", "User counters the AI, testing session memory")
    req_json2 = {
        "userId": USER_ID,
        "session_id": SESSION_ID,
        "topicId": topic_id,
        "difficulty": 4,
        "role": "counter_argument",
        "message": "But setting up new job training programs has historically failed; people need a direct safety net immediately."
    }
    print(f"  User Role: {req_json2['role']}")
    print(f"  User Msg: \"{req_json2['message']}\"")
    print(f"  (Session ID: {SESSION_ID})")
    print(f"  Payload sent:\n  {json.dumps(req_json2, indent=2)}")
    
    resp2 = requests.post(f"{BASE_URL}/training/debate", json=req_json2)
    success2 = resp2.status_code == 200
    print_result(success2, f"Debate API Status {resp2.status_code}", resp2.json() if success2 else resp2.text)


    # --- Scenario 3: Validation Error Edge Case ---
    print_scenario("3", "Testing invalid user role validation")
    req_json3 = {
        "userId": USER_ID,
        "session_id": SESSION_ID,
        "topicId": topic_id,
        "difficulty": 4,
        "role": "fake_role",
        "message": "This should fail validation."
    }
    print(f"  Sending broken payload expecting 422: \n  {json.dumps(req_json3, indent=2)}")
    resp3 = requests.post(f"{BASE_URL}/training/debate", json=req_json3)
    success3 = resp3.status_code == 422
    print_result(success3, f"Caught format error successfully. Status {resp3.status_code}", resp3.json() if success3 else resp3.text)

    print_header("DEBATE COACH TESTS COMPLETE")

if __name__ == "__main__":
    run_tests()
