import requests
import json
import sys

# Ensure utf-8 encoding for printing emojis on Windows
sys.stdout.reconfigure(encoding='utf-8')

BASE_URL = "http://localhost:8000"
USER_ID = 104

def print_header(title):
    print(f"\n{'='*70}")
    print(f" {title}")
    print(f"{'='*70}")

def print_scenario(num, desc):
    print(f"\n--- Scenario {num}: {desc} ---")

def print_result(success, message, payload=None):
    icon = "✅ SUCCESS" if success else "❌ FAILED"
    print(f"  {icon} | {message}")
    if payload:
        if isinstance(payload, dict):
            if "ai_message" in payload:
                print("\n  [AI RESPONSE]:")
                print(f"  \"{payload['ai_message']}\"\n")
            if "structured_data" in payload:
                usage = payload["structured_data"].get("usage", {})
                content = payload["structured_data"].get("practiceContent", {})
                print(f"  [METADATA] Cost: ${usage.get('estimated_cost_usd', 0):.6f} | Difficulty: {content.get('difficulty')} | Generated By: {content.get('generatedBy')}")
            
            print("\n  [FULL RAW RESPONSE PAYLOAD]:")
            print(f"  {json.dumps(payload, indent=2)}")
        else:
            print("\n  [RAW RESPONSE]:")
            print(f"  {payload}")
    
    if not success:
         print("\nStopping tests due to failure.")
         exit(1)

def run_tests():
    print_header("FLOW 04: DIFFICULTY-AWARE TRAINING GENERATOR")
    
    try:
        requests.get(f"{BASE_URL}/health")
    except requests.exceptions.ConnectionError:
        print("❌ ERROR: Server is not running! Please start uvicorn app.main:app --reload first.")
        return

    # Setup
    print("Setting up background data...")
    cat = requests.post(f"{BASE_URL}/categories/", json={"user_id": USER_ID, "category_name": "Economy"}).json()
    top = requests.post(f"{BASE_URL}/topics/", json={"user_id": USER_ID, "category_id": cat.get("category_id", 0), "topic_name": "Fiscal Policy"}).json()
    topic_id = top.get("topic_id", 1)
    print(f"  Topic Setup: ID={topic_id}")
    requests.post(f"{BASE_URL}/topics/{topic_id}/generate-materials", json={"user_id": USER_ID, "topic_id": topic_id, "topic_name": "Fiscal Policy", "difficulty": 3})

    # --- Scenario 1: Beginner Difficulty ---
    print_scenario("1", "Training generator at BEGINNER difficulty")
    req_json = {
        "userId": USER_ID,
        "topicId": topic_id,
        "difficulty": "Beginner",
        "message": "I struggle to explain why lower taxes help the economy."
    }
    print(f"  Difficulty: {req_json['difficulty']}")
    print(f"  User Msg: \"{req_json['message']}\"")
    
    resp1 = requests.post(f"{BASE_URL}/training/generate", json=req_json)
    success1 = resp1.status_code == 200
    data1 = resp1.json() if success1 else resp1.text
    print_result(success1, f"Training API Status {resp1.status_code}", data1)

    # --- Scenario 2: Advanced Difficulty ---
    print_scenario("2", "Training generator at ADVANCED difficulty")
    req_json2 = {
        "userId": USER_ID,
        "topicId": topic_id,
        "difficulty": "Advanced",
        "message": "I struggle to counter arguments supporting modern monetary theory."
    }
    print(f"  Difficulty: {req_json2['difficulty']}")
    print(f"  User Msg: \"{req_json2['message']}\"")
    
    resp2 = requests.post(f"{BASE_URL}/training/generate", json=req_json2)
    success2 = resp2.status_code == 200
    print_result(success2, f"Training API Status {resp2.status_code}", resp2.json() if success2 else resp2.text)

    # --- Scenario 3: Validation Error ---
    print_scenario("3", "Testing invalid difficulty validation")
    req_json3 = {
        "userId": USER_ID,
        "topicId": topic_id,
        "difficulty": "Expert", # Invalid Literal
        "message": "This should fail validation."
    }
    resp3 = requests.post(f"{BASE_URL}/training/generate", json=req_json3)
    success3 = resp3.status_code == 422
    print_result(success3, f"Caught format error successfully. Status {resp3.status_code}", resp3.json() if success3 else resp3.text)

    print_header("TRAINING GENERATOR TESTS COMPLETE")

if __name__ == "__main__":
    run_tests()
