import requests
import json
import sys

# Ensure utf-8 encoding for printing emojis on Windows
sys.stdout.reconfigure(encoding='utf-8')

BASE_URL = "http://localhost:8000"
USER_ID = 104

def print_header(title):
    print(f"\n{'='*70}")
    print(f" {title}")
    print(f"{'='*70}")

def print_scenario(num, desc):
    print(f"\n--- Scenario {num}: {desc} ---")

def print_result(success, message, payload=None):
    icon = "✅ SUCCESS" if success else "❌ FAILED"
    print(f"  {icon} | {message}")
    if payload:
        if isinstance(payload, dict):
            if "ai_message" in payload:
                print("\n  [AI RESPONSE]:")
                print(f"  \"{payload['ai_message']}\"\n")
            if "structured_data" in payload:
                usage = payload["structured_data"].get("usage", {})
                content = payload["structured_data"].get("practiceContent", {})
                print(f"  [METADATA] Cost: ${usage.get('estimated_cost_usd', 0):.6f} | Difficulty: {content.get('difficulty')} | Generated By: {content.get('generatedBy')}")
            
            print("\n  [FULL RAW RESPONSE PAYLOAD]:")
            print(f"  {json.dumps(payload, indent=2)}")
    
    if not success:
         print("\nStopping tests due to failure.")
         exit(1)

def run_tests():
    print_header("FLOW 04: TOPIC CARD GENERATOR")
    
    try:
        requests.get(f"{BASE_URL}/health")
    except requests.exceptions.ConnectionError:
        print("❌ ERROR: Server is not running! Please start uvicorn app.main:app --reload first.")
        return

    # Setup — create a fresh category + topic
    print("Setting up background data...")
    cat = requests.post(f"{BASE_URL}/categories/", json={"user_id": USER_ID, "category_name": "TopicCardTest"})
    if cat.status_code != 200:
        print(f"  ⚠️ Category setup returned {cat.status_code}: {cat.text}")
        return
    cat_data = cat.json()

    top = requests.post(f"{BASE_URL}/topics/", json={
        "user_id": USER_ID, 
        "category_id": cat_data["category_id"], 
        "topic_name": "Nuclear Energy Safety"
    })
    if top.status_code != 200:
        print(f"  ⚠️ Topic setup returned {top.status_code}: {top.text}")
        return
    top_data = top.json()
    topic_id = top_data["topic_id"]
    print(f"  Created topic {topic_id}: Nuclear Energy Safety")

    # Optionally generate materials (non-blocking, gives AI context)
    requests.post(f"{BASE_URL}/topics/{topic_id}/generate-materials", json={
        "user_id": USER_ID, "topic_id": topic_id, 
        "topic_name": "Nuclear Energy Safety", "difficulty": 3
    })

    # --- Scenario 1: Generate a Topic Card ---
    print_scenario("1", "Generate a 4-part argument topic card (no difficulty)")
    req_json = {
        "userId": USER_ID,
        "topicId": topic_id,
        "message": "I struggle to prove that nuclear energy is safe for the environment."
    }
    print(f"  User Msg: \"{req_json['message']}\"")
    print(f"  Payload sent:\n  {json.dumps(req_json, indent=2)}")
    
    resp1 = requests.post(f"{BASE_URL}/topics/generate", json=req_json)
    success1 = resp1.status_code == 200
    data1 = resp1.json() if success1 else resp1.text
    print_result(success1, f"Topic Generate API Status {resp1.status_code}", data1)

    # Verify difficulty is null and no practiceAttempt
    if success1:
        difficulty = data1.get("structured_data", {}).get("practiceContent", {}).get("difficulty")
        has_attempt = "practiceAttempt" in data1.get("structured_data", {})
        print(f"\n  🔍 Difficulty is null: {'✅ YES' if difficulty is None else '❌ NO (got: ' + str(difficulty) + ')'}")
        print(f"  🔍 No practiceAttempt: {'✅ YES' if not has_attempt else '❌ NO (still present)'}")

    # --- Scenario 2: Missing required field ---
    print_scenario("2", "Testing validation — missing 'message' field")
    req_json2 = {
        "userId": USER_ID,
        "topicId": topic_id,
    }
    print(f"  Sending broken payload expecting 422:\n  {json.dumps(req_json2, indent=2)}")
    resp2 = requests.post(f"{BASE_URL}/topics/generate", json=req_json2)
    success2 = resp2.status_code == 422
    print_result(success2, f"Caught validation error. Status {resp2.status_code}", resp2.json() if success2 else resp2.text)

    print_header("TOPIC CARD GENERATOR TESTS COMPLETE")

if __name__ == "__main__":
    run_tests()
